services:
  Simultantesthomeassistant:
    container_name: Testhomeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8124:8123"
    #network_mode: host
    privileged: true
    restart: unless-stopped